/**
 * (C) Copyright 2025- ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 *
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation
 * nor does it submit to any jurisdiction.
 */

#include <vector>

#include "eckit/mpi/Comm.h"

#include "no_wake.h"


namespace wind_farm_plugin {


static WFPModelBuilder<NoWake> NoWakeBuilder;


NoWake::NoWake(const eckit::Configuration& conf) : WFPModel{conf} {
    // do nothing
}


double NoWake::computePower(const WindMap& wMap, const WindFarm& windFarm) const {

    double localPower = computePowerLocal_(wMap, windFarm);

    double globalPower{0};
    eckit::mpi::comm().allReduce(localPower, globalPower, eckit::mpi::sum());

    return globalPower;
}

std::vector<WindPoint> NoWake::computeWindAtPoints(const WindMap& wMap, const WindFarm& windFarm,
                                                   const std::vector<std::unique_ptr<LatLonPoint>>& points) const {

    std::vector<WindPoint> velPoints;
    auto avgWind = windFarm.computeAvgWindSpeed(wMap);

    // Simple possible implementation:
    // associate the average wind speed to every point
    for (const auto& p : points) {
        velPoints.push_back(WindPoint(*p, avgWind.first, avgWind.second));
    }

    return velPoints;
}


/**
 * @brief Calculate the power generated by all local wind turbines
 *
 * @param wMap
 * @param turbines
 * @return double
 */
double NoWake::computePowerLocal_(const WindMap& wMap, const WindFarm& windFarm) const {

    auto arrayU = wMap.arrayU();
    auto arrayV = wMap.arrayV();

    double totalPower_local = 0.0;

    // Calculate the power for each wind turbine
    for (const auto& wt : windFarm.windTurbines()) {

        // horizontal vel components
        size_t nearestPointID = wt->nearestPointID();
        double hubU_ms        = arrayU(nearestPointID, 0);
        double hubV_ms        = arrayV(nearestPointID, 0);

        totalPower_local += wt->computePower(hubU_ms, hubV_ms);
    }

    return totalPower_local;
}


}  // namespace wind_farm_plugin